CREATE DATABASE QuanLyCongVan;
GO
USE QuanLyCongVan;
GO

CREATE TABLE tblLoaiCV (
    MaLoaiCV INT PRIMARY KEY,
    TenLoaiCV NVARCHAR(150) NOT NULL
);

CREATE TABLE tblNhom (
    MaNhom INT PRIMARY KEY,
    TenNhom NVARCHAR(150) NOT NULL
);

CREATE TABLE tblNguoiDung (
    MaND VARCHAR(20) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    MatKhau NVARCHAR(50) NOT NULL,
    Email NVARCHAR(200) NULL,
    TenDN NVARCHAR(50) NOT NULL,
    QuyenHan NCHAR(100) NULL,
    TrangThai INT NULL
);

CREATE TABLE tblNhapNDCV (
    MaCV NCHAR(50) PRIMARY KEY,
    MaLoaiCV INT NOT NULL FOREIGN KEY REFERENCES tblLoaiCV(MaLoaiCV),
    TieuDeCV NVARCHAR(200) NULL,
    NgayGuiNhan NVARCHAR(20) NULL,
    SoCV NVARCHAR(50) NULL,
    CoQuanBanHanh NVARCHAR(150) NULL,
    NgayBanHanh NVARCHAR(50) NULL,
    TrichYeuND NVARCHAR(200) NULL,
    NguoiKy NVARCHAR(50) NULL,
    NoiNhan NVARCHAR(255) NULL,
    TuKhoa NVARCHAR(255) NULL,
    ButPheLanhDao NVARCHAR(255) NULL,
    GuiHayNhan INT NOT NULL,
    GhiChu NVARCHAR(200) NULL
);

CREATE TABLE tblFileDinhKem (
    FileID INT PRIMARY KEY,
    Url NVARCHAR(250) NOT NULL,
    Size INT NULL,
    DateUpload DATETIME NOT NULL,
    MaCV NCHAR(50) NOT NULL FOREIGN KEY REFERENCES tblNhapNDCV(MaCV),
    MoTa NVARCHAR(255) NULL,
    TenFile NVARCHAR(255) NULL
);

CREATE TABLE tblMenu (
    MenuID INT PRIMARY KEY,
    MenuName NVARCHAR(100) NOT NULL,
    MenuUrl NVARCHAR(50) NOT NULL
);

CREATE TABLE tblNhomND (
    MaND NCHAR(50) NOT NULL FOREIGN KEY REFERENCES tblNguoiDung(MaND),
    MaNhom INT NOT NULL FOREIGN KEY REFERENCES tblNhom(MaNhom),
    PRIMARY KEY (MaND, MaNhom)
);
```
