#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCVan
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyCongVan")]
	public partial class InfoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDanhBaEmail(DanhBaEmail instance);
    partial void UpdateDanhBaEmail(DanhBaEmail instance);
    partial void DeleteDanhBaEmail(DanhBaEmail instance);
    partial void InserttblPhongBan(tblPhongBan instance);
    partial void UpdatetblPhongBan(tblPhongBan instance);
    partial void DeletetblPhongBan(tblPhongBan instance);
    partial void InserttblFileDinhKem(tblFileDinhKem instance);
    partial void UpdatetblFileDinhKem(tblFileDinhKem instance);
    partial void DeletetblFileDinhKem(tblFileDinhKem instance);
    partial void InserttblGuiNhan(tblGuiNhan instance);
    partial void UpdatetblGuiNhan(tblGuiNhan instance);
    partial void DeletetblGuiNhan(tblGuiNhan instance);
    partial void InserttblLoaiCV(tblLoaiCV instance);
    partial void UpdatetblLoaiCV(tblLoaiCV instance);
    partial void DeletetblLoaiCV(tblLoaiCV instance);
    partial void InserttblMenu(tblMenu instance);
    partial void UpdatetblMenu(tblMenu instance);
    partial void DeletetblMenu(tblMenu instance);
    partial void InserttblNoiDungCV(tblNoiDungCV instance);
    partial void UpdatetblNoiDungCV(tblNoiDungCV instance);
    partial void DeletetblNoiDungCV(tblNoiDungCV instance);
    partial void InserttblNguoiDung(tblNguoiDung instance);
    partial void UpdatetblNguoiDung(tblNguoiDung instance);
    partial void DeletetblNguoiDung(tblNguoiDung instance);
    partial void InserttblNhom(tblNhom instance);
    partial void UpdatetblNhom(tblNhom instance);
    partial void DeletetblNhom(tblNhom instance);
    partial void InserttblNhomNguoiDung(tblNhomNguoiDung instance);
    partial void UpdatetblNhomNguoiDung(tblNhomNguoiDung instance);
    partial void DeletetblNhomNguoiDung(tblNhomNguoiDung instance);
    #endregion
		
		public InfoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLyCongVanConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public InfoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InfoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InfoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InfoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DanhBaEmail> DanhBaEmails
		{
			get
			{
				return this.GetTable<DanhBaEmail>();
			}
		}
		
		public System.Data.Linq.Table<tblPhongBan> tblPhongBans
		{
			get
			{
				return this.GetTable<tblPhongBan>();
			}
		}
		
		public System.Data.Linq.Table<tblFileDinhKem> tblFileDinhKems
		{
			get
			{
				return this.GetTable<tblFileDinhKem>();
			}
		}
		
		public System.Data.Linq.Table<tblGuiNhan> tblGuiNhans
		{
			get
			{
				return this.GetTable<tblGuiNhan>();
			}
		}
		
		public System.Data.Linq.Table<tblLoaiCV> tblLoaiCVs
		{
			get
			{
				return this.GetTable<tblLoaiCV>();
			}
		}
		
		public System.Data.Linq.Table<tblMenu> tblMenus
		{
			get
			{
				return this.GetTable<tblMenu>();
			}
		}
		
		public System.Data.Linq.Table<tblNoiDungCV> tblNoiDungCVs
		{
			get
			{
				return this.GetTable<tblNoiDungCV>();
			}
		}
		
		public System.Data.Linq.Table<tblNguoiDung> tblNguoiDungs
		{
			get
			{
				return this.GetTable<tblNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<tblNhom> tblNhoms
		{
			get
			{
				return this.GetTable<tblNhom>();
			}
		}
		
		public System.Data.Linq.Table<tblNhomNguoiDung> tblNhomNguoiDungs
		{
			get
			{
				return this.GetTable<tblNhomNguoiDung>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NoiDungCVSelect")]
		public void NoiDungCVSelect([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string searchInfo)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchInfo);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhBaEmail")]
	public partial class DanhBaEmail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Email;
		
		private System.Nullable<int> _SoLanGui;
		
		private int _MaPhongBan;
		
		private string _UserName;
		
		private EntityRef<tblPhongBan> _tblPhongBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSoLanGuiChanging(System.Nullable<int> value);
    partial void OnSoLanGuiChanged();
    partial void OnMaPhongBanChanging(int value);
    partial void OnMaPhongBanChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    #endregion
		
		public DanhBaEmail()
		{
			this._tblPhongBan = default(EntityRef<tblPhongBan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLanGui", DbType="Int")]
		public System.Nullable<int> SoLanGui
		{
			get
			{
				return this._SoLanGui;
			}
			set
			{
				if ((this._SoLanGui != value))
				{
					this.OnSoLanGuiChanging(value);
					this.SendPropertyChanging();
					this._SoLanGui = value;
					this.SendPropertyChanged("SoLanGui");
					this.OnSoLanGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongBan", DbType="Int NOT NULL")]
		public int MaPhongBan
		{
			get
			{
				return this._MaPhongBan;
			}
			set
			{
				if ((this._MaPhongBan != value))
				{
					if (this._tblPhongBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._MaPhongBan = value;
					this.SendPropertyChanged("MaPhongBan");
					this.OnMaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhongBan_DanhBaEmail", Storage="_tblPhongBan", ThisKey="MaPhongBan", OtherKey="MaPhongBan", IsForeignKey=true)]
		public tblPhongBan tblPhongBan
		{
			get
			{
				return this._tblPhongBan.Entity;
			}
			set
			{
				tblPhongBan previousValue = this._tblPhongBan.Entity;
				if (((previousValue != value) 
							|| (this._tblPhongBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPhongBan.Entity = null;
						previousValue.DanhBaEmails.Remove(this);
					}
					this._tblPhongBan.Entity = value;
					if ((value != null))
					{
						value.DanhBaEmails.Add(this);
						this._MaPhongBan = value.MaPhongBan;
					}
					else
					{
						this._MaPhongBan = default(int);
					}
					this.SendPropertyChanged("tblPhongBan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhongBan")]
	public partial class tblPhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhongBan;
		
		private string _TenPhongBan;
		
		private EntitySet<DanhBaEmail> _DanhBaEmails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongBanChanging(int value);
    partial void OnMaPhongBanChanged();
    partial void OnTenPhongBanChanging(string value);
    partial void OnTenPhongBanChanged();
    #endregion
		
		public tblPhongBan()
		{
			this._DanhBaEmails = new EntitySet<DanhBaEmail>(new Action<DanhBaEmail>(this.attach_DanhBaEmails), new Action<DanhBaEmail>(this.detach_DanhBaEmails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongBan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaPhongBan
		{
			get
			{
				return this._MaPhongBan;
			}
			set
			{
				if ((this._MaPhongBan != value))
				{
					this.OnMaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._MaPhongBan = value;
					this.SendPropertyChanged("MaPhongBan");
					this.OnMaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhongBan", DbType="NVarChar(50)")]
		public string TenPhongBan
		{
			get
			{
				return this._TenPhongBan;
			}
			set
			{
				if ((this._TenPhongBan != value))
				{
					this.OnTenPhongBanChanging(value);
					this.SendPropertyChanging();
					this._TenPhongBan = value;
					this.SendPropertyChanged("TenPhongBan");
					this.OnTenPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhongBan_DanhBaEmail", Storage="_DanhBaEmails", ThisKey="MaPhongBan", OtherKey="MaPhongBan")]
		public EntitySet<DanhBaEmail> DanhBaEmails
		{
			get
			{
				return this._DanhBaEmails;
			}
			set
			{
				this._DanhBaEmails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DanhBaEmails(DanhBaEmail entity)
		{
			this.SendPropertyChanging();
			entity.tblPhongBan = this;
		}
		
		private void detach_DanhBaEmails(DanhBaEmail entity)
		{
			this.SendPropertyChanging();
			entity.tblPhongBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblFileDinhKem")]
	public partial class tblFileDinhKem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _FileID;
		
		private string _Url;
		
		private System.Nullable<int> _Size;
		
		private string _DateUpload;
		
		private string _MaCV;
		
		private string _TenFile;
		
		private EntityRef<tblNoiDungCV> _tblNoiDungCV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFileIDChanging(string value);
    partial void OnFileIDChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnSizeChanging(System.Nullable<int> value);
    partial void OnSizeChanged();
    partial void OnDateUploadChanging(string value);
    partial void OnDateUploadChanged();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    partial void OnTenFileChanging(string value);
    partial void OnTenFileChanged();
    #endregion
		
		public tblFileDinhKem()
		{
			this._tblNoiDungCV = default(EntityRef<tblNoiDungCV>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string FileID
		{
			get
			{
				return this._FileID;
			}
			set
			{
				if ((this._FileID != value))
				{
					this.OnFileIDChanging(value);
					this.SendPropertyChanging();
					this._FileID = value;
					this.SendPropertyChanged("FileID");
					this.OnFileIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(250)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Int")]
		public System.Nullable<int> Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpload", DbType="NVarChar(100)")]
		public string DateUpload
		{
			get
			{
				return this._DateUpload;
			}
			set
			{
				if ((this._DateUpload != value))
				{
					this.OnDateUploadChanging(value);
					this.SendPropertyChanging();
					this._DateUpload = value;
					this.SendPropertyChanged("DateUpload");
					this.OnDateUploadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="NVarChar(50)")]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					if (this._tblNoiDungCV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenFile", DbType="NVarChar(255)")]
		public string TenFile
		{
			get
			{
				return this._TenFile;
			}
			set
			{
				if ((this._TenFile != value))
				{
					this.OnTenFileChanging(value);
					this.SendPropertyChanging();
					this._TenFile = value;
					this.SendPropertyChanged("TenFile");
					this.OnTenFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNoiDungCV_tblFileDinhKem", Storage="_tblNoiDungCV", ThisKey="MaCV", OtherKey="MaCV", IsForeignKey=true)]
		public tblNoiDungCV tblNoiDungCV
		{
			get
			{
				return this._tblNoiDungCV.Entity;
			}
			set
			{
				tblNoiDungCV previousValue = this._tblNoiDungCV.Entity;
				if (((previousValue != value) 
							|| (this._tblNoiDungCV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNoiDungCV.Entity = null;
						previousValue.tblFileDinhKems.Remove(this);
					}
					this._tblNoiDungCV.Entity = value;
					if ((value != null))
					{
						value.tblFileDinhKems.Add(this);
						this._MaCV = value.MaCV;
					}
					else
					{
						this._MaCV = default(string);
					}
					this.SendPropertyChanged("tblNoiDungCV");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblGuiNhan")]
	public partial class tblGuiNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCV;
		
		private int _MaNguoiDung;
		
		private EntityRef<tblNoiDungCV> _tblNoiDungCV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    partial void OnMaNguoiDungChanging(int value);
    partial void OnMaNguoiDungChanged();
    #endregion
		
		public tblGuiNhan()
		{
			this._tblNoiDungCV = default(EntityRef<tblNoiDungCV>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					if (this._tblNoiDungCV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNoiDungCV_tblGuiNhan", Storage="_tblNoiDungCV", ThisKey="MaCV", OtherKey="MaCV", IsForeignKey=true)]
		public tblNoiDungCV tblNoiDungCV
		{
			get
			{
				return this._tblNoiDungCV.Entity;
			}
			set
			{
				tblNoiDungCV previousValue = this._tblNoiDungCV.Entity;
				if (((previousValue != value) 
							|| (this._tblNoiDungCV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNoiDungCV.Entity = null;
						previousValue.tblGuiNhans.Remove(this);
					}
					this._tblNoiDungCV.Entity = value;
					if ((value != null))
					{
						value.tblGuiNhans.Add(this);
						this._MaCV = value.MaCV;
					}
					else
					{
						this._MaCV = default(string);
					}
					this.SendPropertyChanged("tblNoiDungCV");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLoaiCV")]
	public partial class tblLoaiCV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiCV;
		
		private string _TenLoaiCV;
		
		private EntitySet<tblNoiDungCV> _tblNoiDungCVs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiCVChanging(int value);
    partial void OnMaLoaiCVChanged();
    partial void OnTenLoaiCVChanging(string value);
    partial void OnTenLoaiCVChanged();
    #endregion
		
		public tblLoaiCV()
		{
			this._tblNoiDungCVs = new EntitySet<tblNoiDungCV>(new Action<tblNoiDungCV>(this.attach_tblNoiDungCVs), new Action<tblNoiDungCV>(this.detach_tblNoiDungCVs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiCV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiCV
		{
			get
			{
				return this._MaLoaiCV;
			}
			set
			{
				if ((this._MaLoaiCV != value))
				{
					this.OnMaLoaiCVChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiCV = value;
					this.SendPropertyChanged("MaLoaiCV");
					this.OnMaLoaiCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiCV", DbType="NVarChar(150)")]
		public string TenLoaiCV
		{
			get
			{
				return this._TenLoaiCV;
			}
			set
			{
				if ((this._TenLoaiCV != value))
				{
					this.OnTenLoaiCVChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiCV = value;
					this.SendPropertyChanged("TenLoaiCV");
					this.OnTenLoaiCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLoaiCV_tblNoiDungCV", Storage="_tblNoiDungCVs", ThisKey="MaLoaiCV", OtherKey="MaLoaiCV")]
		public EntitySet<tblNoiDungCV> tblNoiDungCVs
		{
			get
			{
				return this._tblNoiDungCVs;
			}
			set
			{
				this._tblNoiDungCVs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblNoiDungCVs(tblNoiDungCV entity)
		{
			this.SendPropertyChanging();
			entity.tblLoaiCV = this;
		}
		
		private void detach_tblNoiDungCVs(tblNoiDungCV entity)
		{
			this.SendPropertyChanging();
			entity.tblLoaiCV = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMenu")]
	public partial class tblMenu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MenuID;
		
		private string _MenuName;
		
		private string _MenuURL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuIDChanging(int value);
    partial void OnMenuIDChanged();
    partial void OnMenuNameChanging(string value);
    partial void OnMenuNameChanged();
    partial void OnMenuURLChanging(string value);
    partial void OnMenuURLChanged();
    #endregion
		
		public tblMenu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MenuID
		{
			get
			{
				return this._MenuID;
			}
			set
			{
				if ((this._MenuID != value))
				{
					this.OnMenuIDChanging(value);
					this.SendPropertyChanging();
					this._MenuID = value;
					this.SendPropertyChanged("MenuID");
					this.OnMenuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuName", DbType="NVarChar(50)")]
		public string MenuName
		{
			get
			{
				return this._MenuName;
			}
			set
			{
				if ((this._MenuName != value))
				{
					this.OnMenuNameChanging(value);
					this.SendPropertyChanging();
					this._MenuName = value;
					this.SendPropertyChanged("MenuName");
					this.OnMenuNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuURL", DbType="NVarChar(50)")]
		public string MenuURL
		{
			get
			{
				return this._MenuURL;
			}
			set
			{
				if ((this._MenuURL != value))
				{
					this.OnMenuURLChanging(value);
					this.SendPropertyChanging();
					this._MenuURL = value;
					this.SendPropertyChanged("MenuURL");
					this.OnMenuURLChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNoiDungCV")]
	public partial class tblNoiDungCV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCV;
		
		private System.Nullable<int> _MaLoaiCV;
		
		private string _TieuDeCV;
		
		private System.Nullable<System.DateTime> _NgayGui;
		
		private string _SoCV;
		
		private string _CoQuanBanHanh;
		
		private System.Nullable<System.DateTime> _NgayBanHanh;
		
		private string _TrichYeuND;
		
		private string _NguoiKy;
		
		private string _NoiNhan;
		
		private string _TuKhoa;
		
		private System.Nullable<bool> _TrangThai;
		
		private System.Nullable<int> _GuiHayNhan;
		
		private string _GhiChu;
		
		private EntitySet<tblFileDinhKem> _tblFileDinhKems;
		
		private EntitySet<tblGuiNhan> _tblGuiNhans;
		
		private EntityRef<tblLoaiCV> _tblLoaiCV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    partial void OnMaLoaiCVChanging(System.Nullable<int> value);
    partial void OnMaLoaiCVChanged();
    partial void OnTieuDeCVChanging(string value);
    partial void OnTieuDeCVChanged();
    partial void OnNgayGuiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGuiChanged();
    partial void OnSoCVChanging(string value);
    partial void OnSoCVChanged();
    partial void OnCoQuanBanHanhChanging(string value);
    partial void OnCoQuanBanHanhChanged();
    partial void OnNgayBanHanhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBanHanhChanged();
    partial void OnTrichYeuNDChanging(string value);
    partial void OnTrichYeuNDChanged();
    partial void OnNguoiKyChanging(string value);
    partial void OnNguoiKyChanged();
    partial void OnNoiNhanChanging(string value);
    partial void OnNoiNhanChanged();
    partial void OnTuKhoaChanging(string value);
    partial void OnTuKhoaChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    partial void OnGuiHayNhanChanging(System.Nullable<int> value);
    partial void OnGuiHayNhanChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tblNoiDungCV()
		{
			this._tblFileDinhKems = new EntitySet<tblFileDinhKem>(new Action<tblFileDinhKem>(this.attach_tblFileDinhKems), new Action<tblFileDinhKem>(this.detach_tblFileDinhKems));
			this._tblGuiNhans = new EntitySet<tblGuiNhan>(new Action<tblGuiNhan>(this.attach_tblGuiNhans), new Action<tblGuiNhan>(this.detach_tblGuiNhans));
			this._tblLoaiCV = default(EntityRef<tblLoaiCV>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiCV", DbType="Int")]
		public System.Nullable<int> MaLoaiCV
		{
			get
			{
				return this._MaLoaiCV;
			}
			set
			{
				if ((this._MaLoaiCV != value))
				{
					if (this._tblLoaiCV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiCVChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiCV = value;
					this.SendPropertyChanged("MaLoaiCV");
					this.OnMaLoaiCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeCV", DbType="NVarChar(200)")]
		public string TieuDeCV
		{
			get
			{
				return this._TieuDeCV;
			}
			set
			{
				if ((this._TieuDeCV != value))
				{
					this.OnTieuDeCVChanging(value);
					this.SendPropertyChanging();
					this._TieuDeCV = value;
					this.SendPropertyChanged("TieuDeCV");
					this.OnTieuDeCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGui", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGui
		{
			get
			{
				return this._NgayGui;
			}
			set
			{
				if ((this._NgayGui != value))
				{
					this.OnNgayGuiChanging(value);
					this.SendPropertyChanging();
					this._NgayGui = value;
					this.SendPropertyChanged("NgayGui");
					this.OnNgayGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCV", DbType="NVarChar(200)")]
		public string SoCV
		{
			get
			{
				return this._SoCV;
			}
			set
			{
				if ((this._SoCV != value))
				{
					this.OnSoCVChanging(value);
					this.SendPropertyChanging();
					this._SoCV = value;
					this.SendPropertyChanged("SoCV");
					this.OnSoCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoQuanBanHanh", DbType="NVarChar(300)")]
		public string CoQuanBanHanh
		{
			get
			{
				return this._CoQuanBanHanh;
			}
			set
			{
				if ((this._CoQuanBanHanh != value))
				{
					this.OnCoQuanBanHanhChanging(value);
					this.SendPropertyChanging();
					this._CoQuanBanHanh = value;
					this.SendPropertyChanged("CoQuanBanHanh");
					this.OnCoQuanBanHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBanHanh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayBanHanh
		{
			get
			{
				return this._NgayBanHanh;
			}
			set
			{
				if ((this._NgayBanHanh != value))
				{
					this.OnNgayBanHanhChanging(value);
					this.SendPropertyChanging();
					this._NgayBanHanh = value;
					this.SendPropertyChanged("NgayBanHanh");
					this.OnNgayBanHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrichYeuND", DbType="NVarChar(500)")]
		public string TrichYeuND
		{
			get
			{
				return this._TrichYeuND;
			}
			set
			{
				if ((this._TrichYeuND != value))
				{
					this.OnTrichYeuNDChanging(value);
					this.SendPropertyChanging();
					this._TrichYeuND = value;
					this.SendPropertyChanged("TrichYeuND");
					this.OnTrichYeuNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiKy", DbType="NVarChar(30)")]
		public string NguoiKy
		{
			get
			{
				return this._NguoiKy;
			}
			set
			{
				if ((this._NguoiKy != value))
				{
					this.OnNguoiKyChanging(value);
					this.SendPropertyChanging();
					this._NguoiKy = value;
					this.SendPropertyChanged("NguoiKy");
					this.OnNguoiKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiNhan", DbType="NVarChar(255)")]
		public string NoiNhan
		{
			get
			{
				return this._NoiNhan;
			}
			set
			{
				if ((this._NoiNhan != value))
				{
					this.OnNoiNhanChanging(value);
					this.SendPropertyChanging();
					this._NoiNhan = value;
					this.SendPropertyChanged("NoiNhan");
					this.OnNoiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuKhoa", DbType="NVarChar(255)")]
		public string TuKhoa
		{
			get
			{
				return this._TuKhoa;
			}
			set
			{
				if ((this._TuKhoa != value))
				{
					this.OnTuKhoaChanging(value);
					this.SendPropertyChanging();
					this._TuKhoa = value;
					this.SendPropertyChanged("TuKhoa");
					this.OnTuKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuiHayNhan", DbType="Int")]
		public System.Nullable<int> GuiHayNhan
		{
			get
			{
				return this._GuiHayNhan;
			}
			set
			{
				if ((this._GuiHayNhan != value))
				{
					this.OnGuiHayNhanChanging(value);
					this.SendPropertyChanging();
					this._GuiHayNhan = value;
					this.SendPropertyChanged("GuiHayNhan");
					this.OnGuiHayNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(200)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNoiDungCV_tblFileDinhKem", Storage="_tblFileDinhKems", ThisKey="MaCV", OtherKey="MaCV")]
		public EntitySet<tblFileDinhKem> tblFileDinhKems
		{
			get
			{
				return this._tblFileDinhKems;
			}
			set
			{
				this._tblFileDinhKems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNoiDungCV_tblGuiNhan", Storage="_tblGuiNhans", ThisKey="MaCV", OtherKey="MaCV")]
		public EntitySet<tblGuiNhan> tblGuiNhans
		{
			get
			{
				return this._tblGuiNhans;
			}
			set
			{
				this._tblGuiNhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLoaiCV_tblNoiDungCV", Storage="_tblLoaiCV", ThisKey="MaLoaiCV", OtherKey="MaLoaiCV", IsForeignKey=true)]
		public tblLoaiCV tblLoaiCV
		{
			get
			{
				return this._tblLoaiCV.Entity;
			}
			set
			{
				tblLoaiCV previousValue = this._tblLoaiCV.Entity;
				if (((previousValue != value) 
							|| (this._tblLoaiCV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblLoaiCV.Entity = null;
						previousValue.tblNoiDungCVs.Remove(this);
					}
					this._tblLoaiCV.Entity = value;
					if ((value != null))
					{
						value.tblNoiDungCVs.Add(this);
						this._MaLoaiCV = value.MaLoaiCV;
					}
					else
					{
						this._MaLoaiCV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblLoaiCV");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblFileDinhKems(tblFileDinhKem entity)
		{
			this.SendPropertyChanging();
			entity.tblNoiDungCV = this;
		}
		
		private void detach_tblFileDinhKems(tblFileDinhKem entity)
		{
			this.SendPropertyChanging();
			entity.tblNoiDungCV = null;
		}
		
		private void attach_tblGuiNhans(tblGuiNhan entity)
		{
			this.SendPropertyChanging();
			entity.tblNoiDungCV = this;
		}
		
		private void detach_tblGuiNhans(tblGuiNhan entity)
		{
			this.SendPropertyChanging();
			entity.tblNoiDungCV = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNguoiDung")]
	public partial class tblNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguoiDung;
		
		private string _Email;
		
		private string _TenDN;
		
		private string _MatKhau;
		
		private string _QuyenHan;
		
		private System.Nullable<int> _TrangThai;
		
		private string _HoTen;
		
		private int _MaNhom;
		
		private EntitySet<tblNhomNguoiDung> _tblNhomNguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTenDNChanging(string value);
    partial void OnTenDNChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnQuyenHanChanging(string value);
    partial void OnQuyenHanChanged();
    partial void OnTrangThaiChanging(System.Nullable<int> value);
    partial void OnTrangThaiChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnMaNhomChanging(int value);
    partial void OnMaNhomChanged();
    #endregion
		
		public tblNguoiDung()
		{
			this._tblNhomNguoiDungs = new EntitySet<tblNhomNguoiDung>(new Action<tblNhomNguoiDung>(this.attach_tblNhomNguoiDungs), new Action<tblNhomNguoiDung>(this.detach_tblNhomNguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDN", DbType="NVarChar(50)")]
		public string TenDN
		{
			get
			{
				return this._TenDN;
			}
			set
			{
				if ((this._TenDN != value))
				{
					this.OnTenDNChanging(value);
					this.SendPropertyChanging();
					this._TenDN = value;
					this.SendPropertyChanged("TenDN");
					this.OnTenDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyenHan", DbType="NChar(20)")]
		public string QuyenHan
		{
			get
			{
				return this._QuyenHan;
			}
			set
			{
				if ((this._QuyenHan != value))
				{
					this.OnQuyenHanChanging(value);
					this.SendPropertyChanging();
					this._QuyenHan = value;
					this.SendPropertyChanged("QuyenHan");
					this.OnQuyenHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="Int NOT NULL")]
		public int MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNguoiDung_tblNhomNguoiDung", Storage="_tblNhomNguoiDungs", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung")]
		public EntitySet<tblNhomNguoiDung> tblNhomNguoiDungs
		{
			get
			{
				return this._tblNhomNguoiDungs;
			}
			set
			{
				this._tblNhomNguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblNhomNguoiDungs(tblNhomNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.tblNguoiDung = this;
		}
		
		private void detach_tblNhomNguoiDungs(tblNhomNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.tblNguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhom")]
	public partial class tblNhom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhom;
		
		private string _MoTa;
		
		private EntitySet<tblNhomNguoiDung> _tblNhomNguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(int value);
    partial void OnMaNhomChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public tblNhom()
		{
			this._tblNhomNguoiDungs = new EntitySet<tblNhomNguoiDung>(new Action<tblNhomNguoiDung>(this.attach_tblNhomNguoiDungs), new Action<tblNhomNguoiDung>(this.detach_tblNhomNguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(200)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhom_tblNhomNguoiDung", Storage="_tblNhomNguoiDungs", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<tblNhomNguoiDung> tblNhomNguoiDungs
		{
			get
			{
				return this._tblNhomNguoiDungs;
			}
			set
			{
				this._tblNhomNguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblNhomNguoiDungs(tblNhomNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.tblNhom = this;
		}
		
		private void detach_tblNhomNguoiDungs(tblNhomNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.tblNhom = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhomNguoiDung")]
	public partial class tblNhomNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguoiDung;
		
		private int _MaNhom;
		
		private EntityRef<tblNguoiDung> _tblNguoiDung;
		
		private EntityRef<tblNhom> _tblNhom;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    partial void OnMaNhomChanging(int value);
    partial void OnMaNhomChanged();
    #endregion
		
		public tblNhomNguoiDung()
		{
			this._tblNguoiDung = default(EntityRef<tblNguoiDung>);
			this._tblNhom = default(EntityRef<tblNhom>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					if (this._tblNguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._tblNhom.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNguoiDung_tblNhomNguoiDung", Storage="_tblNguoiDung", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public tblNguoiDung tblNguoiDung
		{
			get
			{
				return this._tblNguoiDung.Entity;
			}
			set
			{
				tblNguoiDung previousValue = this._tblNguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._tblNguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNguoiDung.Entity = null;
						previousValue.tblNhomNguoiDungs.Remove(this);
					}
					this._tblNguoiDung.Entity = value;
					if ((value != null))
					{
						value.tblNhomNguoiDungs.Add(this);
						this._MaNguoiDung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoiDung = default(string);
					}
					this.SendPropertyChanged("tblNguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhom_tblNhomNguoiDung", Storage="_tblNhom", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public tblNhom tblNhom
		{
			get
			{
				return this._tblNhom.Entity;
			}
			set
			{
				tblNhom previousValue = this._tblNhom.Entity;
				if (((previousValue != value) 
							|| (this._tblNhom.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhom.Entity = null;
						previousValue.tblNhomNguoiDungs.Remove(this);
					}
					this._tblNhom.Entity = value;
					if ((value != null))
					{
						value.tblNhomNguoiDungs.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(int);
					}
					this.SendPropertyChanged("tblNhom");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
