//------------------------------------------------------------------------------
// <auto-generated>
//     Mã này được tạo tự động.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCVan
{
    public partial class SuaCV
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.ValidationSummary vs1;

        protected global::System.Web.UI.WebControls.Label lblTieuDe;
        protected global::System.Web.UI.WebControls.TextBox txttieude;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTieuDe;

        protected global::System.Web.UI.WebControls.Label lblSoCV;
        protected global::System.Web.UI.WebControls.TextBox txtsocv;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSoCV;

        protected global::System.Web.UI.WebControls.Label lblLoaiCV;
        protected global::System.Web.UI.WebControls.DropDownList ddlLoaiCV;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLoaiCV;

        protected global::System.Web.UI.WebControls.Label lblNgayBanHanh;
        protected global::System.Web.UI.WebControls.TextBox txtngaybanhanh;

        protected global::System.Web.UI.WebControls.Label lblNgayGui;
        protected global::System.Web.UI.WebControls.TextBox txtngaygui;

        protected global::System.Web.UI.WebControls.Label lblCoQuanBanHanh;
        protected global::System.Web.UI.WebControls.TextBox txtcqbh;

        protected global::System.Web.UI.WebControls.Label lblDonViNhan;
        protected global::System.Web.UI.WebControls.DropDownList ddlDonViNhan;

        protected global::System.Web.UI.WebControls.Label lblGuiNhan;
        protected global::System.Web.UI.WebControls.RadioButtonList RadioButtonList1;

        protected global::System.Web.UI.WebControls.Label lblTrichYeu;
        protected global::System.Web.UI.WebControls.TextBox txttrichyeu;

        protected global::System.Web.UI.WebControls.Label lblGhiChu;
        protected global::System.Web.UI.WebControls.TextBox txtGhiChu;

        protected global::System.Web.UI.WebControls.Label lblNguoiKy;
        protected global::System.Web.UI.WebControls.TextBox txtNguoiKy;

        protected global::System.Web.UI.WebControls.Label lblFileCu;
        protected global::System.Web.UI.WebControls.FileUpload FileUpload1;
        protected global::System.Web.UI.WebControls.HiddenField hfFileCu;
        protected global::System.Web.UI.WebControls.ListBox ListBox1;

        protected global::System.Web.UI.WebControls.Button btnUp;
        protected global::System.Web.UI.WebControls.Button btnRemove;
        protected global::System.Web.UI.WebControls.Button btnReAll;

        protected global::System.Web.UI.WebControls.Button btnBack;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
